# Copyright 2023 iwatake2222
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Class to manage graph (NetworkX)"""
from __future__ import annotations
import os
import re
import networkx as nx
import pydot
from .logger_factory import LoggerFactory
from .caret2networkx import caret2networkx
from .caret_extend_callback_group import extend_callback_group
from .caret_extend_agnocast import extend_agnocast
from .agnocast_extend_runtime import extend_agnocast_runtime
from .caret_extend_path import get_path_dict
from .dot2networkx import dot2networkx
from .ros2networkx import Ros2Networkx
from .graph_layout import place_node_by_group
from .mermaid_exporter import save_graph_to_mermaid
from .agnocast_extend_utils import AGNOCAST_NODE_ATTRS, AGNOCAST_EDGE_ATTRS

logger = LoggerFactory.create(__name__)


def save_agnocast_dot(graph: nx.MultiDiGraph, dot_path: str) -> None:
  """Overwrite a dot file with Agnocast attributes added to nodes and edges.

  Reads the existing dot file, annotates nodes and edges with Agnocast
  attributes from the NetworkX graph, and overwrites the file.
  Only node-only format dots are supported (as generated by ros2networkx).

  Parameters
  ----------
  graph : nx.MultiDiGraph
      Graph with Agnocast attributes already set by extend_agnocast_runtime().
  dot_path : str
      Path to the dot file to overwrite.
  """
  try:
    graphs = pydot.graph_from_dot_file(dot_path)
  except Exception as e:
    logger.error('Failed to read dot file for Agnocast annotation: %s', e)
    return

  if not graphs:
    logger.error('No graph found in dot file: %s', dot_path)
    return

  dot_graph = graphs[0]

  # Build lookups:
  #   label (e.g. '/node_src') -> pydot Node object
  #   label -> pydot node ID   (for referencing in Edge creation)
  label_to_dot_node: dict[str, pydot.Node] = {}
  label_to_dot_id: dict[str, str] = {}
  for dot_node in dot_graph.get_nodes():
    attrs = dot_node.get_attributes()
    label = attrs.get('label', '').strip('"')
    if label:
      label_to_dot_node[label] = dot_node
      label_to_dot_id[label] = dot_node.get_name()

  # Annotate nodes
  for node_name in graph.nodes:
    bare = node_name.strip('"')
    dot_node = label_to_dot_node.get(bare)
    if dot_node is None:
      # ③ node not in original dot — add it
      new_node = pydot.Node(
        node_name,
        label=node_name,
        shape='ellipse',
      )
      dot_graph.add_node(new_node)
      dot_node = new_node
      # Register in lookups so edges can reference this node
      label_to_dot_node[bare] = new_node
      label_to_dot_id[bare] = new_node.get_name()
    for attr in AGNOCAST_NODE_ATTRS:
      val = graph.nodes[node_name].get(attr)
      if val is not None:
        dot_node.set(attr, str(val))

  # Build lookup for edges: (src_label, dst_label, topic_label) -> pydot edge
  dot_edge_lookup: dict[tuple[str, str, str], pydot.Edge] = {}
  for dot_edge in dot_graph.get_edges():
    src_id = dot_edge.get_source().strip('"')
    dst_id = dot_edge.get_destination().strip('"')
    edge_attrs = dot_edge.get_attributes()
    topic = edge_attrs.get('label', '').strip('"')
    # src_id / dst_id are dot node IDs (e.g. 'n___node_src'), resolve to label
    src_node = dot_graph.get_node(src_id)
    dst_node = dot_graph.get_node(dst_id)
    if src_node and dst_node:
      src_label = src_node[0].get_attributes().get('label', '').strip('"')
      dst_label = dst_node[0].get_attributes().get('label', '').strip('"')
      dot_edge_lookup[(src_label, dst_label, topic)] = dot_edge

  # Annotate edges / add new ③ edges
  for src, dst, key in graph.edges:
    edge_data = graph.edges[src, dst, key]
    topic = edge_data.get('label', '').strip('"')
    src_bare = src.strip('"')
    dst_bare = dst.strip('"')

    dot_edge = dot_edge_lookup.get((src_bare, dst_bare, topic))
    if dot_edge is None:
      # Edge added by extend_agnocast_runtime (③ node edge) — add to dot.
      # Use pydot node IDs (not NetworkX names) so the edge references
      # the correct nodes in the dot graph.
      src_dot_id = label_to_dot_id.get(src_bare, src)
      dst_dot_id = label_to_dot_id.get(dst_bare, dst)
      new_edge = pydot.Edge(src_dot_id, dst_dot_id, label=topic)
      dot_graph.add_edge(new_edge)
      dot_edge = new_edge

    for attr in AGNOCAST_EDGE_ATTRS:
      val = edge_data.get(attr)
      if val is not None:
        dot_edge.set(attr, str(val))

  try:
    dot_graph.write(dot_path)
    logger.info('Agnocast dot saved: %s', dot_path)
  except Exception as e:
    logger.error('Failed to write Agnocast-annotated dot: %s', e)


class GraphManager:
  """Class to manage graph (NetworkX)"""
  def __init__(self, app_setting, group_setting):
    self.app_setting = app_setting
    self.group_setting = group_setting
    self.dir = './'
    self.graph: nx.DiGraph = nx.MultiDiGraph()
    self.caret_path_dict: dict = {}

  def load_graph_from_caret(self, filename: str, target_path: str = 'all_graph'):
    """ load_graph_from_caret """
    self.graph = caret2networkx(filename, target_path,
                  self.app_setting['display_unconnected_nodes'])
    self.graph = extend_callback_group(filename, self.graph)
    self.graph = extend_agnocast(filename, self.graph)
    self.load_graph_postprocess(filename)
    self.caret_path_dict.update(get_path_dict(filename))

  def load_graph_from_dot(self, filename: str,
               save_agnocast_dot_path: str | None = None):
    """ load_graph_from_dot """
    self.graph = dot2networkx(filename, self.app_setting['display_unconnected_nodes'])
    self.graph = extend_agnocast_runtime(self.graph)
    if save_agnocast_dot_path:
      save_agnocast_dot(self.graph, save_agnocast_dot_path)
    self.load_graph_postprocess(filename)

  def load_graph_from_running_ros(self):
    """ load_graph_from_running_ros """
    ros2networkx = Ros2Networkx(node_name='temp')
    dot_path = './temp.dot'
    ros2networkx.save_graph(dot_path)
    ros2networkx.shutdown()
    self.load_graph_from_dot(dot_path, save_agnocast_dot_path=dot_path)

  def load_graph_postprocess(self, filename):
    """ Common process after loading graph """
    self.dir = os.path.dirname(filename) + '/' if os.path.dirname(filename) != '' else './'
    self.clear_caret_path_dict()
    self.filter_topic()     # delete topic before node
    self.filter_node()
    if len(self.graph.nodes):
      self.graph = place_node_by_group(self.graph, self.group_setting)
      # self.graph = align_layout(self.graph)

  def filter_node(self):
    """Remove nodes which match filter setting"""
    remove_node_list = []
    for node_name in self.graph.nodes:
      node_name_org = node_name.strip('"')
      for pattern in self.app_setting['ignore_node_list']:
        if re.fullmatch(pattern, node_name_org):
          remove_node_list.append(node_name)
          break
    self.graph.remove_nodes_from(remove_node_list)
    logger.info('%s nodes are removed by filter', len(remove_node_list))

    if not self.app_setting['display_unconnected_nodes']:
      isolated_node_list = list(nx.isolates(self.graph))
      logger.info('%s nodes are removed due to isolated', len(isolated_node_list))
      self.graph.remove_nodes_from(isolated_node_list)

  def filter_topic(self):
    """Remove topics which match filter setting"""
    remove_edge_list = []
    for edge in self.graph.edges:
      topic_name = self.graph.edges[edge]['label']
      topic_name = topic_name.strip('"')
      for pattern in self.app_setting['ignore_topic_list']:
        if re.fullmatch(pattern, topic_name):
          remove_edge_list.append(edge)
          break
    self.graph.remove_edges_from(remove_edge_list)
    logger.info('%s topics are removed by filter', len(remove_edge_list))

  def clear_caret_path_dict(self):
    """ Clear CARET path dict """
    self.caret_path_dict.clear()
    self.caret_path_dict['<< CLEAR >>'] = []

  def export_to_mermaid(self, output_dir: str | None = None) -> str:
    """
    Export current graph to Mermaid HTML file
    
    Args:
        output_dir: Output directory path. If None, uses self.dir
    
    Returns:
        str: Path to saved HTML file
    """
    target_dir = output_dir if output_dir is not None else self.dir
    html_path = save_graph_to_mermaid(self.graph, target_dir)
    return html_path
